### ISSUE TITLE
AppKey 및 SecretKey 자동 저장 기능 요청

### ISSUE THREAD

**Issue by emiant0** [teranum/eBEST.OpenApi.DevCenter#1]
올려주신 DevCenter 감사히 잘쓰겠습니다. 
매번 실행할때마다 AppKey와 SecretKey를 ID/Password 처럼 기억을 할수가 없어서 매번 따로 저장된 내용을 붙여넣기하는게 귀챦네요.
AppKey와 SecretKey 저장하는 기능 추가해주셨으면 합니다.

**Comment by teranum** [comment]
소스수정은 아래 위치 살펴보시면 됩니다.
https://github.com/teranum/eBEST.OpenApi.DevCenter/blob/1fa5d30e2fd6149301cff831d6af82926a53d5dc/eBEST.OpenApi.DevCenter/ViewModels/MainViewModel.cs#L119C3-L119C3

#if DEBUG, #endif 라인 삭제 하시면 됩니다 (135, 131, 123, 119 라인 삭제)

**Comment by teranum** [comment]
릴리즈버전에 키저장버전 같이 올려놨습니다.

https://github.com/teranum/eBEST.OpenApi.DevCenter/releases
